server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:/liquibase/changelog-root.yml
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: bb3aebefdbb8372a6eb1
            client-secret: da32a143e54e08cde874378f345ea75688514f11